ui : fixing username not appearing
inveniosoftware/invenio-requests pull request #319
Opened 2023-06-07 10:05 UTC by TLGINO

* shows user email if no username or display_name is found and email_visibility != restricted
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2229

2023-06-07 12:54 UTC, ntarocco commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || (user.preferences.email_visibility != "restricted" ? user.email : "")}</span>
It would be even better if we serialize the `user` obj using the permissions, when injecting it in the UI. See [here](https://github.com/inveniosoftware/invenio-users-resources/blob/master/invenio_users_resources/services/schemas.py#L44).
This will take advantage of the current configured permissions, and we avoid hardcoding these checks (which can be very easily forgotten!)

2023-06-07 16:15 UTC, ntarocco commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || (user.preferences.email_visibility != "restricted" ? user.email : "")}</span>
Very valid point, even if the username is not required in the db (see [here](https://github.com/inveniosoftware/invenio-userprofiles/blob/master/invenio_userprofiles/alembic/c25ef2c50ffa_create_userprofiles_tables.py#L26)), the username is required in the registration form, see [here](https://github.com/inveniosoftware/invenio-userprofiles/blob/master/invenio_userprofiles/forms.py#L59).

So, I would say that in most of the cases, the `username` will be there.
What about:
```
full_name || user.username || user.email || <translated>Unknown user</translated>
```
?

2023-06-07 16:17 UTC, anikachurilova commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || (user.preferences.email_visibility != "restricted" ? user.email : "")}</span>
Looks good to me :)

2023-06-09 14:02 UTC, anikachurilova requested changes

2023-06-09 14:02 UTC, anikachurilova commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || user.email || <translated>Unknown user</translated>}</span>
Does this `<translated/>` tag exist? I think Nico put it to comment just to show, that we have to make this text translatable.
Usually we use `i18next` to translate strings is JavaScript files. See example here: https://github.com/inveniosoftware/invenio-app-rdm/blob/2c552805cacce4fe77abac975b5c8cc117c73e1b/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js#LL137C5-L137C5

2023-06-09 14:05 UTC, TLGINO commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || user.email || <translated>Unknown user</translated>}</span>
oh whoops I'll fix it thx!

2023-06-12 07:38 UTC, anikachurilova commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user.username || user.email || i18next.t("Unknown user")}
question: does it make sense here to use the chain operators? e.g: `{user.profile?.full_name || user?.username || user?.email || i18next.t("Unknown user")}`

2023-06-12 08:32 UTC, anikachurilova approved these changes

2023-06-15 11:52 UTC, kpsherva commented on invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
> +    <span>{user.profile?.full_name || user?.username || user?.email || i18next.t("Unknown user")}
```suggestion
    <span>{user.profile?.full_name || user?.username || user?.email || i18next.t("Anonymous user")}
```

2023-06-19 15:02 UTC, jrcastro2 approved these changes

2023-07-11 08:54 UTC, zzacharo approved these changes

2023-07-11 08:54 UTC, merged